# This is a basic workflow to help you get started with Actions

name: api-docs-build

on:
  push:
    branches:
      - dev-api

jobs:
  # First run our unit tests - make sure they all pass
  test:
    runs-on: ubuntu-latest
    steps:

    # Check out the development branch for the api
      - uses: actions/checkout@v3
        with:
          ref: dev-api

    # Run npm install and then run units tests
      - name: Run Unit Tests
        run: |
          npm install
          npm test     
  push:
    # Require that the previous job, "test" was successful
    needs: test
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Check out the development branch for the website
      - uses: actions/checkout@v3
        with:
          ref: dev-web
          fetch-depth: 0
          
      # Configure github username and email
      - name: Config User and Email
        run: |
          git config user.name ${{ github.event.pusher.name }} 
          git config user.email ${{ github.event.pusher.email }}

      # Pushes API changes to the development branch for the website
      - name: Fetch and Merge API Changes
        run: |
          git fetch origin
          git checkout origin/dev-api -- src --allow-unrelated-histories --strategy-option=theirs
          
      - name: Push API Changes
        run:
          git push
          
    
    
