# This is a basic workflow to help you get started with Actions

name: api-docs-build

on:
  push:
    branches:
      - main

jobs:
  
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          ref: gh-pages

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          git config --global user.email "peter.t.walsh@stonybrook.edu"
          git config --global user.name "PeteyLumpkins"
          git fetch origin
          git merge origin/main
          git commit -m "Updating Readme from main branch"
          git push
