# This is a basic workflow to help you get started with Actions

name: Build

on: 
  push: 
    branches:
      - dev-api

jobs:
  # Check to make sure the engine compiles first - mission critical
  Compile:
    uses: ./.github/workflows/compile.yml
    with:
      branch: ${{ github.ref_name }}

  # Run Unit Tests - lets check and see if the unit tests pass
  Test:
    needs: Compile
    uses: ./.github/workflows/test.yml
    with:
      branch: ${{ github.ref_name }}

  # Builds and adds the documentation files for the api. 
  Docs:
    needs: Compile
    uses: ./.github/workflows/document.yml
    with:
      branch: ${{ github.ref_name }}
      username: ${{ github.event.pusher.name }}
      email: ${{ github.event.pusher.email }}
      message: Committing documentation

      
