# This is a basic workflow to help you get started with Actions

name: Compile

on: 
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
jobs:
  Compile:
    runs-on: ubuntu-latest
    steps: 
      - name: Show Branch
        run: echo ${{ inputs.branch }}

      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.branch }}

      - name: Compile Test
        run: |
          npm install
          npm run build