# This is a basic workflow to help you get started with Actions

name: Deploy

on: 
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'     
        required: true
        default: 'v0.0.0'
      branch:
        description: 'Branch to pull from'
        required: true
        default: 'dev-api'

jobs:

  # Validates the version number given as input
  Validate Version:
    runs-on: ubuntu-latest
    steps:
      - run: |
          npm install semver
          npx semver ${{ github.event.inputs.version }}

  # Check to make sure the engine compiles first - mission critical
  Compile:
    needs: Validate Version
    uses: ./.github/workflows/compile.yml

  # Run Unit Tests - lets check and see if the unit tests pass
  Test:
    needs: Compile
    uses: ./.github/workflows/test.yml

  # Builds and adds the documentation files for the api. 
  Docs:
    needs: Compile
    uses: ./.github/workflows/document.yml