# This is a basic workflow to help you get started with Actions

name: Deploy

on: 
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'     
        required: true
        default: 'v0.0.0'
      branch:
        description: 'Branch to pull from'
        required: true
        default: 'dev-api'

jobs:

  # Validates the version number given as input
  Version:
    runs-on: ubuntu-latest
    steps:
      - name: Check Semantic Version
        run: |
          npm install semver
          npx semver ${{ github.event.inputs.version }}

  # Check to make sure the engine compiles first - mission critical
  Compile:
    needs: Version
    uses: ./.github/workflows/compile.yml
    with:
      branch: ${{ inputs.branch }}

  # Run Unit Tests - lets check and see if the unit tests pass
  Test:
    needs: Compile
    uses: ./.github/workflows/test.yml
    with:
      branch: ${{ inputs.branch }}

  # Fetch and merge from the development branch
  Pull:
    needs: Test
    runs-on: ubuntu-latest
    steps:

      # Get the development branch
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}

      # Configure github username and email
      - name: Config User and Email
        run: |
          git config user.name ${{ github.actor }} 

      # Fetch and Merge
      - name: Fetch and Merge
        run: |
          git fetch origin
          git merge origin/${{ inputs.branch }} --allow-unrelated-histories --strategy-option=theirs

      # Tag the commit and push to main branch
      - name: Tag, Commit, Push
        run: |
          # git commit -m "Pushing changes. Testing. Hellow World!"
          git tag ${{ inputs.version }}
          git push
