# This is a basic workflow to help you get started with Actions

name: Document

on: 
  workflow_call:
    inputs:
      # The name of the branch where the docs are going to be generated
      branch:
        required: true
        type: string
      # The username to use for documentation commit
      username:
        required: true
        type: string
      # The email to use for the documentation commit
      email: 
        required: true
        type: string
      # The message to be sent when the documentation is committed
      message:
        required: true
        type: string
jobs:

  Document:
    runs-on: ubuntu-latest
    steps:

      # Check out the whatever branch we're on
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.branch }}
      
      # Setup OpenJDK - this is for the UML diagrams
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin' 
          java-version: '17'

      # Setup GraphViz - this is also for the UML diagrams
      - uses: ts-graphviz/setup-graphviz@v1

      - name: Build API Docs
        run: |
          npm install
          npm run docs

      # Configure github username and email
      - name: Config User and Email
        run: |
          git config user.name ${{ inputs.username }} 
          git config user.email ${{ inputs.email }}

      # Add, commit, and push the docs to remote development branch
      - name: Git ACP
        run: |
          git add .
          git commit -m ${{ inputs.message }}
          git push