# This is a basic workflow to help you get started with Actions

name: Document

on: 
  workflow_call:

jobs:

  Document:
    runs-on: ubuntu-latest
    steps:

      # Check out the whatever branch we're on
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}
      
      # Setup OpenJDK - this is for the UML diagrams
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin' 
          java-version: '17'

      # Setup GraphViz - this is also for the UML diagrams
      - uses: ts-graphviz/setup-graphviz@v1

      - name: Build API Docs
        run: |
          npm install
          npm run docs

      # Configure github username and email
      - name: Config User and Email
        run: |
          git config user.name ${{ github.event.pusher.name }} 
          git config user.email ${{ github.event.pusher.email }}

      # Add, commit, and push the docs to remote development branch
      - name: Git ACP
        run: |
          git add .
          git commit -m "Adding docs to remote"
          git push