# This is a basic workflow to help you get started with Actions

name: api-docs-build

on:
  workflow_call

jobs:
  # Build the engine 
  Compile:
    uses: "./.github/workflows/build.yml"

  # Run Unit Tests
  Test:
    needs: Compile
    runs-on: ubuntu-latest
    steps:

    # Check out the development branch for the api
      - uses: actions/checkout@v3
        with:
          ref: dev-api

    # Run npm install and then run units tests
      - name: Run Unit Tests
        run: |
          npm install
          npm test  